const mongoose = require('mongoose');

const replySchema = new mongoose.Schema({
  message: {
    type: String,
    required: true,
  },
  senderType: {
    type: String,
    enum: ['OrganizationUser', 'SystemAdmin'],
    required: true,
  },
  user: {
    _id: { type: String },
    name: { type: String },
    email: { type: String }
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  timestamp: {
    type: Date,
    default: Date.now,
  }
});

const supportTicketSchema = new mongoose.Schema({
  organization: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Organization',
    required: true,
  },
  createdBy: {
    _id: { type: String, required: true },
    name: { type: String },
    email: { type: String }
  },
  feature: {
    type: String,
    required: true,
    enum: [
      'Dashboard', 'Members', 'Groups & Households', 'Committees', 
      'BMD Records', 'Events & Fundraisers', 'Finance & Ledgers', 
      'Settings & Profile', 'Other'
    ],
    default: 'Other'
  },
  issueName: {
    type: String,
    required: true,
    trim: true,
  },
  description: {
    type: String,
    required: true,
  },
  status: {
    type: String,
    enum: ['Open', 'In Progress', 'Resolved', 'Closed'],
    default: 'Open',
  },
  priority: {
    type: String,
    enum: ['Low', 'Medium', 'High', 'Critical'],
    default: 'Medium',
  },
  replies: [replySchema],
}, {
  timestamps: true,
});

const SupportTicket = mongoose.model('SupportTicket', supportTicketSchema);

module.exports = SupportTicket;
